.

diff --git a/cs35l/hw/a3/submit/poornames b/cs35l/hw/a3/submit/poornames
--- a/cs35l/hw/a3/submit/poornames
+++ b/cs35l/hw/a3/submit/poornames
@@ -1,122 +1,106 @@
-#!/bin/bash
+D=null
+ARGS=$#
+R=false
+IFS=$'\n'
 
-recursive=false
-GLOBIGNORE=.
 
-isValidDir()
-{
-    if [[ ${#1} -gt 14 ]];
-    then
-        false
-    elif [[ $1 =~ .*[^A-Za-z_.-].* ]];
-    then
-        false
-    elif [[ $1 =~ ^\.{1,2}[^.]*$ ]];
-    then
-        false
-    elif [[ $1 =~ ^-.*$ ]];
-    then
-        false
-    else
-        true
-    fi
-}
-
-searchInvalidName()
-{
-    local search_path="$1"
-    local filedata=`ls -aF $search_path`
-    
-    for file in $filedata
-    do
-        if [[ $file == "../" ]];
-        then continue
-        elif [[ $file == "./" ]];
-        then continue
-        fi
-
-        if ! $2;
-        then
-            echo "$search_path/$file"
-        elif [[ $file =~ ^.*\/$ ]];
-        then
-            echo "$search_path/$file"
-            if $recursive;
-            then
-                local next_dir="$search_path/$file"
-                local valid=$(isValidDir "${next_dir%?}")
-                searchInvalidName "${next_dir%?}" $valid
-            fi
-        elif [[ ${#file} -gt 14 ]];
-        then
-            echo "$search_path/$file"
-        elif [[ $file =~ .*[^A-Za-z_.-].* ]];
-        then
-            echo "$search_path/$file"
-        elif [[ $file =~ ^\.{1,2}[^.]*$ ]];
-        then
-            echo "$search_path/$file"
-        elif [[ $file =~ ^-.*$ ]];
-        then
-            echo "$search_path/$file"
-        else
-            for other in $filedata
-            do
-                if [[ "$file" == "$other" ]];
-                then 
-                    continue
-                else
-                    shopt -s nocasematch
-                    if [[ "$file" == "$other" ]];
-                    then
-                        echo "$search_path/$file"
-                        shopt -u nocasematch
-                        break
-                    fi
-                    shopt -u nocasematch
-                fi
-            done
-        fi
-        
-    done
-}
-
-dir=null
-if (($# == 1))
-then
-    dir=$1
-    if [ ! -d "$1" ];
-    then
-        echo "The specified directory does not exist." >&2
-        exit 1
-    fi
-elif (($# == 2))
-then
-    dir=$2
-    if [[ "$1" != "-r" ]]
-    then
-        echo "Invalid option." >&2
-        exit 1
-    else
-        
-        if [ ! -d "$2" ];
-        then
-            echo "The specified directory does not exist." >&2
-            exit 1
-        fi
-        recursive=true
-    fi
-else
-    echo "Invalid number of arguments." >&2
+if (($ARGS == 0))
+then 
+    echo "Error: Empty input" >&2
     exit 1
 fi
 
-dir_raw=$(echo $dir | tr "/" "\n")
-dir_valid=true
-for component in dir_raw
-do
-    if ! isValidDir $component;
-    then $dir_valid=false
+if (($ARGS > 2))
+then
+    echo "Error: Too many arguments." >&2
+    exit 1
+fi
+
+if (($ARGS == 2))
+then
+    if [ "${1:0:2}" != "-r" ]
+    then
+	echo "Error: Incorrect option." >&2
+	exit 1
     fi
-done
-searchInvalidName $dir $dir_valid
+
+    if [ "${2:0:1}" == "-" ]
+    then
+	echo "Error: Cannot start with '-'." >&2
+	exit 1
+    fi
+
+    R=true
+    D=$2
+fi
+
+if (($ARGS == 1))
+then
+    if [ "${1:0:2}" == "-r" ]
+    then
+	R=true
+    else
+	D=$1
+    fi
+fi
+
+if [ !  -d "${D}" ]
+then
+    echo "Error: Not a directory." >&2
+    exit 1
+fi
+
+if [ !  -r "${D}" ]
+then
+    echo "Error: No permission." >&2
+fi
+
+
+poorname_r()
+{
+    local DIR=$1
+
+    poorname $DIR
+    
+    directory=$(find "$DIR" -mindepth 1 -maxdepth 1 -type d \-exec basename {} \; | sed 's/ /\\ /g')
+    for item in $directory;
+    do
+	poorname_r  "$DIR/$item"
+    done
+}
+
+poorname()
+{   
+    
+    local DIR=$1
+    if [ ! -r "${DIR}" ]
+    then
+        echo "Error: No permission" >&2
+    fi
+
+    files=$(find "$DIR" -mindepth 1 -maxdepth 1 -exec basename {} \; | sed 's/ /\\ /g')
+    #d=$(find "$DIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sed 's/ /\\ /g')
+    
+    invalid=$(echo "$files" | grep -E "^\.[a-zA-z_-]|^\.{2}[a-zA-z_-]|[^a-zA-Z\._-]|^-|[a-zA-Z\._-]{15,}")
+
+    duplicates=$(echo "$files" | sort -f | uniq -id)
+
+    inv_names=$({ echo "$invalid"; echo "$duplicates"; } | sort -u)
+
+    for item in $inv_names;
+    do
+        if [ -d "$DIR/$item" ]; then
+            echo "$DIR/$item/"
+        else
+	        echo $DIR/$item
+        fi
+    done
+}
+
+
+if [ "$R" != "true" ]
+then
+    poorname $D
+else
+    poorname_r $D
+fi
